export type RouteMethod = "GET" | "HEAD" | "POST" | "PUT" | "PATCH" | "DELETE" | "PROPFIND";
export type RouteSideEffect = "read" | "write" | "communicative" | "destructive";
export type RouteStatus = "supported" | "experimental" | "documented-only" | "deprecated";

export interface RouteParameter {
  name: string;
  location: "path" | "query" | "body";
  required: boolean;
  description: string;
}

export interface RouteDefinition {
  id: string;
  module: string;
  method: RouteMethod;
  path: string;
  summary: string;
  description: string;
  authentication: "session" | "basic" | "matrix-bearer" | "public";
  capability?: string;
  sideEffect: RouteSideEffect;
  status: RouteStatus;
  parameters: RouteParameter[];
  pagination?: { limit?: string; cursor?: string; offset?: string };
  provenance: {
    kind: "official-docs" | "upstream-sdk" | "matrix-spec" | "live-contract";
    reference: string;
  };
  lastVerified?: string;
  compatibility?: string;
}

export interface RouteSearchOptions {
  module?: string;
  method?: RouteMethod;
  sideEffect?: RouteSideEffect;
  status?: RouteStatus;
  limit?: number;
}

const p = (
  name: string,
  location: RouteParameter["location"],
  required: boolean,
  description: string,
): RouteParameter => ({ name, location, required, description });
const upstream = (reference: string) => ({ kind: "upstream-sdk" as const, reference });
const liveContract = (reference: string) => ({ kind: "live-contract" as const, reference });

export const ROUTES = [
  {
    id: "auth.login",
    module: "auth",
    method: "POST",
    path: "/iserv/auth/login",
    summary: "Create a normal-user web session",
    description:
      "Submits the instance login form, including hidden fields and interactive challenges.",
    authentication: "public",
    sideEffect: "write",
    status: "supported",
    parameters: [
      p("_username", "body", true, "Account name"),
      p("_password", "body", true, "Account password"),
    ],
    provenance: upstream("src/Auth/AuthService.ts"),
  },
  {
    id: "auth.logout",
    module: "auth",
    method: "GET",
    path: "/iserv/auth/logout",
    summary: "End the current session",
    description: "Logs out the current web session and clears local session state.",
    authentication: "session",
    sideEffect: "destructive",
    status: "supported",
    parameters: [],
    provenance: upstream("src/Auth/AuthService.ts"),
  },
  {
    id: "account.get",
    module: "account",
    method: "GET",
    path: "/iserv/account/my",
    summary: "Read the signed-in account",
    description: "Returns account metadata for the current user.",
    authentication: "session",
    sideEffect: "read",
    status: "supported",
    parameters: [],
    provenance: upstream("src/User/UserService.ts"),
    lastVerified: "2026-07-20",
  },
  {
    id: "profile.get",
    module: "account",
    method: "GET",
    path: "/iserv/profile/public/edit",
    summary: "Read editable profile data",
    description: "Loads the current user's editable public profile form.",
    authentication: "session",
    sideEffect: "read",
    status: "supported",
    parameters: [],
    provenance: upstream("src/User/UserService.ts"),
    lastVerified: "2026-07-20",
  },
  {
    id: "profile.update",
    module: "account",
    method: "POST",
    path: "/iserv/profile/public/edit",
    summary: "Update the public profile",
    description: "Submits fields supported by the user's profile form.",
    authentication: "session",
    sideEffect: "write",
    status: "supported",
    parameters: [p("fields", "body", true, "Validated profile fields")],
    provenance: upstream("src/User/UserService.ts"),
  },
  {
    id: "users.show",
    module: "users",
    method: "GET",
    path: "/iserv/addressbook/public/show/{username}",
    summary: "Read a visible user profile",
    description: "Returns public address-book information visible to the signed-in account.",
    authentication: "session",
    sideEffect: "read",
    status: "supported",
    parameters: [p("username", "path", true, "IServ account name")],
    provenance: upstream("src/User/UserService.ts"),
    lastVerified: "2026-07-20",
  },
  {
    id: "users.search",
    module: "users",
    method: "GET",
    path: "/iserv/addressbook/public",
    summary: "Search the address book",
    description: "Searches users visible to the current account.",
    authentication: "session",
    sideEffect: "read",
    status: "supported",
    parameters: [p("filter[search]", "query", true, "Search text")],
    pagination: { limit: "limit", offset: "offset" },
    provenance: upstream("src/User/UserService.ts"),
    lastVerified: "2026-07-20",
  },
  {
    id: "users.autocomplete",
    module: "users",
    method: "GET",
    path: "/iserv/core/autocomplete/api",
    summary: "Autocomplete user or group names",
    description: "Returns bounded autocomplete suggestions for supported modules.",
    authentication: "session",
    sideEffect: "read",
    status: "supported",
    parameters: [
      p("query", "query", true, "Search prefix"),
      p("limit", "query", false, "Maximum results"),
    ],
    pagination: { limit: "limit" },
    provenance: upstream("src/User/UserService.ts"),
    lastVerified: "2026-07-20",
  },
  {
    id: "notifications.list",
    module: "notifications",
    method: "GET",
    path: "/iserv/user/api/notifications",
    summary: "List notifications",
    description: "Returns notification state visible to the current account.",
    authentication: "session",
    sideEffect: "read",
    status: "supported",
    parameters: [p("since", "query", false, "Notification cursor")],
    pagination: { cursor: "since" },
    provenance: upstream("src/Notifications/NotificationService.ts"),
    lastVerified: "2026-07-20",
  },
  {
    id: "notifications.badges",
    module: "notifications",
    method: "GET",
    path: "/iserv/app/navigation/badges",
    summary: "Read navigation badges",
    description: "Returns unread counters for installed modules.",
    authentication: "session",
    sideEffect: "read",
    status: "supported",
    parameters: [],
    provenance: upstream("src/Notifications/NotificationService.ts"),
    lastVerified: "2026-07-20",
  },
  {
    id: "notifications.read_all",
    module: "notifications",
    method: "POST",
    path: "/iserv/notification/api/v1/notifications/readall",
    summary: "Mark all notifications read",
    description: "Changes all currently visible notifications to read.",
    authentication: "session",
    sideEffect: "write",
    status: "supported",
    parameters: [],
    provenance: upstream("src/Notifications/NotificationService.ts"),
  },
  {
    id: "calendar.upcoming",
    module: "calendar",
    method: "GET",
    path: "/iserv/calendar/api/upcoming",
    summary: "List upcoming calendar events",
    description: "Returns upcoming events from subscribed calendars.",
    authentication: "session",
    sideEffect: "read",
    status: "supported",
    parameters: [p("limit", "query", false, "Maximum events")],
    pagination: { limit: "limit" },
    provenance: upstream("src/Calendar/CalendarService.ts"),
    lastVerified: "2026-07-20",
  },
  {
    id: "calendar.sources",
    module: "calendar",
    method: "GET",
    path: "/iserv/calendar/api/eventsources",
    summary: "List event sources",
    description: "Lists calendars and event sources visible to the account.",
    authentication: "session",
    sideEffect: "read",
    status: "supported",
    parameters: [],
    provenance: upstream("src/Calendar/CalendarService.ts"),
    lastVerified: "2026-07-20",
  },
  {
    id: "calendar.events",
    module: "calendar",
    method: "GET",
    path: "/iserv/calendar/feed/calendar-multi",
    summary: "Read events in a range",
    description: "Returns calendar events for a requested time range.",
    authentication: "session",
    sideEffect: "read",
    status: "supported",
    parameters: [p("start", "query", true, "Range start"), p("end", "query", true, "Range end")],
    provenance: upstream("src/Calendar/CalendarService.ts"),
    lastVerified: "2026-07-20",
  },
  {
    id: "calendar.create",
    module: "calendar",
    method: "POST",
    path: "/iserv/calendar/create",
    summary: "Create an event",
    description: "Creates an event in a writable calendar using its CSRF-protected form.",
    authentication: "session",
    capability: "calendar:write",
    sideEffect: "communicative",
    status: "supported",
    parameters: [p("event", "body", true, "Validated event fields")],
    provenance: upstream("src/Calendar/CalendarService.ts"),
  },
  {
    id: "calendar.delete",
    module: "calendar",
    method: "POST",
    path: "/iserv/calendar/delete",
    summary: "Delete an event",
    description: "Deletes an event if the account has permission.",
    authentication: "session",
    capability: "calendar:write",
    sideEffect: "destructive",
    status: "supported",
    parameters: [p("id", "body", true, "Event identifier")],
    provenance: upstream("src/Calendar/CalendarService.ts"),
  },
  {
    id: "calendar.caldav",
    module: "calendar",
    method: "PROPFIND",
    path: "/caldav/{calendar}",
    summary: "Discover or synchronize calendars",
    description: "Uses the official CalDAV interface with normal account credentials.",
    authentication: "basic",
    sideEffect: "read",
    status: "documented-only",
    parameters: [p("calendar", "path", true, "Calendar collection")],
    provenance: { kind: "official-docs", reference: "https://doku.iserv.de/modules/calendar/" },
  },
  {
    id: "files.webdav",
    module: "files",
    method: "PROPFIND",
    path: "/webdav",
    summary: "Browse files over WebDAV",
    description: "Uses the official WebDAV interface with normal account credentials.",
    authentication: "basic",
    sideEffect: "read",
    status: "supported",
    parameters: [p("path", "query", false, "Remote path")],
    provenance: {
      kind: "official-docs",
      reference: "https://doku.iserv.de/cookbook/external/webdav/",
    },
    lastVerified: "2026-07-20",
  },
  {
    id: "files.size",
    module: "files",
    method: "GET",
    path: "/iserv/file/calc",
    summary: "Calculate folder size",
    description: "Returns the calculated size of an accessible file path.",
    authentication: "session",
    sideEffect: "read",
    status: "supported",
    parameters: [p("path", "query", true, "Accessible file path")],
    provenance: upstream("src/Files/FilesService.ts"),
    lastVerified: "2026-07-20",
  },
  {
    id: "files.quota",
    module: "files",
    method: "GET",
    path: "/iserv/du/account",
    summary: "Read account disk usage",
    description: "Returns storage usage and quota data.",
    authentication: "session",
    sideEffect: "read",
    status: "supported",
    parameters: [],
    provenance: upstream("src/Files/FilesService.ts"),
    lastVerified: "2026-07-20",
  },
  {
    id: "mail.list",
    module: "mail",
    method: "GET",
    path: "/iserv/mail/api/v2/account/{accountId}/message",
    summary: "List email messages",
    description: "Returns bounded message metadata for a mailbox.",
    authentication: "session",
    sideEffect: "read",
    status: "supported",
    parameters: [
      p("accountId", "path", true, "Mail account identifier"),
      p("limit", "query", false, "Maximum messages"),
    ],
    pagination: { limit: "limit", offset: "offset" },
    provenance: upstream("src/Email/EmailService.ts"),
    lastVerified: "2026-07-20",
  },
  {
    id: "mail.message",
    module: "mail",
    method: "GET",
    path: "/iserv/mail/api/v2/account/{accountId}/mailbox/{mailboxId}/message/{uid}",
    summary: "Read an email message",
    description: "Returns one message visible to the current account.",
    authentication: "session",
    sideEffect: "read",
    status: "supported",
    parameters: [
      p("accountId", "path", true, "Mail account"),
      p("mailboxId", "path", true, "Mailbox"),
      p("uid", "path", true, "Message UID"),
    ],
    provenance: upstream("src/Email/EmailService.ts"),
  },
  {
    id: "mail.flags",
    module: "mail",
    method: "PATCH",
    path: "/iserv/mail/api/v2/account/{accountId}/mailbox/{mailboxId}/message/{uid}",
    summary: "Change email flags",
    description: "Marks an email read or unread.",
    authentication: "session",
    sideEffect: "write",
    status: "supported",
    parameters: [p("flags", "body", true, "Message flags")],
    provenance: upstream("src/Email/EmailService.ts"),
  },
  {
    id: "mail.send",
    module: "mail",
    method: "POST",
    path: "smtp://{instance}:465",
    summary: "Send email via SMTP",
    description: "Sends email using the account's official mail service and credentials.",
    authentication: "basic",
    sideEffect: "communicative",
    status: "supported",
    parameters: [p("message", "body", true, "Recipients, subject, body, and attachments")],
    provenance: upstream("src/Email/EmailService.ts"),
  },
  {
    id: "messenger.authenticate",
    module: "messenger",
    method: "POST",
    path: "/iserv/messenger/authenticate",
    summary: "Create a scoped Matrix session",
    description:
      "Exchanges the current IServ web session for a Matrix access token kept in memory.",
    authentication: "session",
    sideEffect: "write",
    status: "supported",
    parameters: [],
    provenance: upstream("src/Auth/AuthService.ts"),
    lastVerified: "2026-07-20",
  },
  {
    id: "messenger.sync",
    module: "messenger",
    method: "GET",
    path: "/_matrix/client/v3/sync",
    summary: "Synchronize rooms",
    description: "Returns joined rooms and incremental Matrix state.",
    authentication: "matrix-bearer",
    sideEffect: "read",
    status: "supported",
    parameters: [
      p("since", "query", false, "Sync token"),
      p("timeout", "query", false, "Long-poll timeout"),
    ],
    pagination: { cursor: "since" },
    provenance: { kind: "matrix-spec", reference: "Matrix Client-Server API v3" },
    lastVerified: "2026-07-20",
  },
  {
    id: "messenger.messages",
    module: "messenger",
    method: "GET",
    path: "/_matrix/client/v3/rooms/{roomId}/messages",
    summary: "List room messages",
    description: "Returns a bounded page of messages from a joined room.",
    authentication: "matrix-bearer",
    sideEffect: "read",
    status: "supported",
    parameters: [
      p("roomId", "path", true, "Matrix room ID"),
      p("limit", "query", false, "Maximum events"),
    ],
    pagination: { limit: "limit", cursor: "from" },
    provenance: upstream("src/Messenger/MessengerService.ts"),
    lastVerified: "2026-07-20",
  },
  {
    id: "messenger.send",
    module: "messenger",
    method: "PUT",
    path: "/_matrix/client/v3/rooms/{roomId}/send/m.room.message/{txnId}",
    summary: "Send a room message",
    description: "Immediately sends a message to a joined room.",
    authentication: "matrix-bearer",
    sideEffect: "communicative",
    status: "supported",
    parameters: [
      p("roomId", "path", true, "Room ID"),
      p("txnId", "path", true, "Unique transaction ID"),
      p("message", "body", true, "Message body"),
    ],
    provenance: upstream("src/Messenger/MessengerService.ts"),
  },
  {
    id: "messenger.leave",
    module: "messenger",
    method: "POST",
    path: "/_matrix/client/v3/rooms/{roomId}/leave",
    summary: "Leave a room",
    description: "Immediately leaves a joined Matrix room.",
    authentication: "matrix-bearer",
    sideEffect: "destructive",
    status: "supported",
    parameters: [p("roomId", "path", true, "Room ID")],
    provenance: upstream("src/Messenger/MessengerService.ts"),
  },
  {
    id: "messenger.redact",
    module: "messenger",
    method: "PUT",
    path: "/_matrix/client/v3/rooms/{roomId}/redact/{eventId}/{txnId}",
    summary: "Delete a message or reaction",
    description: "Redacts an event when the account has permission.",
    authentication: "matrix-bearer",
    sideEffect: "destructive",
    status: "supported",
    parameters: [p("roomId", "path", true, "Room ID"), p("eventId", "path", true, "Event ID")],
    provenance: upstream("src/Messenger/MessengerService.ts"),
  },
  {
    id: "account.info",
    module: "account",
    method: "GET",
    path: "/iserv/account/info",
    summary: "Read account information",
    description: "Loads the signed-in account's information and login overview.",
    authentication: "session",
    sideEffect: "read",
    status: "supported",
    parameters: [],
    provenance: liveContract("sanitized normal-user GET contract"),
    lastVerified: "2026-07-20",
  },
  {
    id: "account.settings",
    module: "account",
    method: "GET",
    path: "/iserv/account/settings",
    summary: "Read account settings",
    description: "Loads account settings without submitting any changes.",
    authentication: "session",
    sideEffect: "read",
    status: "supported",
    parameters: [],
    provenance: liveContract("sanitized normal-user GET contract"),
    lastVerified: "2026-07-20",
  },
  {
    id: "account.last_logins",
    module: "account",
    method: "GET",
    path: "/iserv/account/info/last_logins",
    summary: "Read recent account logins",
    description: "Loads the security-oriented recent-login overview for the signed-in account.",
    authentication: "session",
    sideEffect: "read",
    status: "supported",
    parameters: [],
    provenance: liveContract("sanitized normal-user GET contract"),
    lastVerified: "2026-07-20",
  },
  {
    id: "users.personal",
    module: "users",
    method: "GET",
    path: "/iserv/addressbook/personal",
    summary: "Read the personal address book",
    description: "Loads personal address-book entries without adding or changing contacts.",
    authentication: "session",
    sideEffect: "read",
    status: "supported",
    parameters: [p("filter[search]", "query", false, "Optional contact search")],
    provenance: liveContract("sanitized normal-user GET contract"),
    lastVerified: "2026-07-20",
  },
  {
    id: "users.messenger_autocomplete",
    module: "users",
    method: "GET",
    path: "/iserv/autocomplete/api/autocomplete",
    summary: "Search messenger recipients",
    description: "Returns bounded recipient suggestions visible to the account.",
    authentication: "session",
    sideEffect: "read",
    status: "supported",
    parameters: [
      p("query", "query", true, "Search text"),
      p("limit", "query", false, "Maximum results"),
    ],
    pagination: { limit: "limit" },
    provenance: upstream("src/User/UserService.ts"),
    lastVerified: "2026-07-20",
  },
  {
    id: "users.avatar",
    module: "users",
    method: "GET",
    path: "/iserv/core/avatar/user/{username}",
    summary: "Read a visible user avatar",
    description: "Returns the avatar image visible for a validated account name.",
    authentication: "session",
    sideEffect: "read",
    status: "supported",
    parameters: [p("username", "path", true, "IServ account name")],
    provenance: upstream("src/User/UserService.ts"),
    lastVerified: "2026-07-20",
  },
  {
    id: "notifications.read",
    module: "notifications",
    method: "POST",
    path: "/iserv/notification/api/v1/notifications/{id}/read",
    summary: "Mark one notification read",
    description: "Changes one visible notification to read when invoked.",
    authentication: "session",
    sideEffect: "write",
    status: "supported",
    parameters: [p("id", "path", true, "Notification identifier")],
    provenance: upstream("src/Notifications/NotificationService.ts"),
  },
  {
    id: "calendar.overview",
    module: "calendar",
    method: "GET",
    path: "/iserv/calendar",
    summary: "Read the calendar overview",
    description: "Loads the calendar application without creating or changing events.",
    authentication: "session",
    sideEffect: "read",
    status: "supported",
    parameters: [],
    provenance: liveContract("sanitized normal-user GET contract"),
    lastVerified: "2026-07-20",
  },
  {
    id: "calendar.search",
    module: "calendar",
    method: "GET",
    path: "/iserv/calendar/api/lookup_event",
    summary: "Search calendar events",
    description: "Searches visible events inside a bounded time range.",
    authentication: "session",
    sideEffect: "read",
    status: "supported",
    parameters: [
      p("summary", "query", true, "Search text"),
      p("start", "query", true, "Range start in milliseconds"),
      p("end", "query", true, "Range end in milliseconds"),
    ],
    provenance: upstream("src/Calendar/CalendarService.ts"),
    lastVerified: "2026-07-20",
  },
  {
    id: "calendar.plugin_events",
    module: "calendar",
    method: "GET",
    path: "/iserv/calendar4/plugin",
    summary: "Read calendar plugin events",
    description: "Returns events from one installed calendar plugin in a bounded range.",
    authentication: "session",
    sideEffect: "read",
    status: "experimental",
    parameters: [
      p("plugin", "query", true, "Plugin identifier"),
      p("start", "query", true, "Range start (YYYY-MM-DD)"),
      p("end", "query", true, "Range end (YYYY-MM-DD)"),
    ],
    provenance: liveContract("calendar4 plugin feed for holiday/exam-plan/exercise"),
    lastVerified: "2026-07-20",
    compatibility:
      "Prefer calendar.holidays for Ferien countdown; raw plugin feed stays experimental.",
  },
  {
    id: "calendar.holidays",
    module: "calendar",
    method: "GET",
    path: "/iserv/calendar4/plugin",
    summary: "School holiday countdown",
    description:
      "Combines Ferien & Feiertage plugin data with movable free days from calendars into a countdown overview.",
    authentication: "session",
    sideEffect: "read",
    status: "supported",
    parameters: [
      p("limit", "query", false, "Maximum upcoming free periods"),
      p("next", "query", false, "If true, focus on upcoming free days"),
    ],
    provenance: liveContract("holiday plugin + calendar-multi movable days"),
    lastVerified: "2026-07-20",
  },
  {
    id: "files.overview",
    module: "files",
    method: "GET",
    path: "/iserv/file",
    summary: "Read the file overview",
    description: "Loads visible file metadata without uploading, moving, or deleting files.",
    authentication: "session",
    sideEffect: "read",
    status: "supported",
    parameters: [],
    provenance: liveContract("sanitized same-origin redirect and GET contract"),
    lastVerified: "2026-07-20",
  },
  {
    id: "mail.overview",
    module: "mail",
    method: "GET",
    path: "/iserv/mail",
    summary: "Read the mail overview",
    description: "Loads mailbox availability without opening or changing a message.",
    authentication: "session",
    sideEffect: "read",
    status: "supported",
    parameters: [],
    provenance: liveContract("sanitized normal-user GET contract"),
    lastVerified: "2026-07-20",
  },
  {
    id: "messenger.overview",
    module: "messenger",
    method: "GET",
    path: "/iserv/messenger",
    summary: "Read messenger availability",
    description: "Loads the local messenger entry point without sending messages or receipts.",
    authentication: "session",
    sideEffect: "read",
    status: "supported",
    parameters: [],
    provenance: liveContract("sanitized same-origin redirect and GET contract"),
    lastVerified: "2026-07-20",
  },
  {
    id: "messenger.members",
    module: "messenger",
    method: "GET",
    path: "/_matrix/client/v3/rooms/{roomId}/members",
    summary: "List room members",
    description: "Returns current members of a joined Matrix room.",
    authentication: "matrix-bearer",
    sideEffect: "read",
    status: "supported",
    parameters: [p("roomId", "path", true, "Room identifier")],
    provenance: upstream("src/Messenger/MessengerService.ts"),
    lastVerified: "2026-07-20",
  },
  {
    id: "messenger.profile",
    module: "messenger",
    method: "GET",
    path: "/_matrix/client/v3/profile/{userId}",
    summary: "Read a Matrix user profile",
    description: "Returns the visible display name and avatar for a Matrix user.",
    authentication: "matrix-bearer",
    sideEffect: "read",
    status: "supported",
    parameters: [p("userId", "path", true, "Matrix user identifier")],
    provenance: upstream("src/Messenger/MessengerService.ts"),
    lastVerified: "2026-07-20",
  },
  {
    id: "messenger.direct_form",
    module: "messenger",
    method: "GET",
    path: "/iserv/messenger/form/directmessage/create",
    summary: "Load direct-message creation form",
    description: "Loads the CSRF-protected form without creating a conversation.",
    authentication: "session",
    sideEffect: "read",
    status: "supported",
    parameters: [],
    provenance: upstream("src/Messenger/MessengerService.ts"),
    lastVerified: "2026-07-20",
  },
  {
    id: "messenger.create_direct",
    module: "messenger",
    method: "POST",
    path: "/iserv/messenger/form/directmessage/create",
    summary: "Create a direct conversation",
    description: "Immediately creates a direct-message room for a selected recipient.",
    authentication: "session",
    sideEffect: "communicative",
    status: "supported",
    parameters: [p("recipient", "body", true, "Validated recipient identifier")],
    provenance: upstream("src/Messenger/MessengerService.ts"),
  },
  {
    id: "messenger.react",
    module: "messenger",
    method: "PUT",
    path: "/_matrix/client/v3/rooms/{roomId}/send/m.reaction/{txnId}",
    summary: "React to a message",
    description: "Immediately sends a Matrix reaction event.",
    authentication: "matrix-bearer",
    sideEffect: "communicative",
    status: "supported",
    parameters: [
      p("roomId", "path", true, "Room identifier"),
      p("txnId", "path", true, "Transaction identifier"),
      p("reaction", "body", true, "Reaction and target event"),
    ],
    provenance: upstream("src/Messenger/MessengerService.ts"),
  },
  {
    id: "app.legal",
    module: "app",
    method: "GET",
    path: "/iserv/app/legal",
    summary: "Read app legal information",
    description: "Loads legal and application information exposed to normal users.",
    authentication: "session",
    sideEffect: "read",
    status: "supported",
    parameters: [],
    provenance: liveContract("sanitized normal-user GET contract"),
    lastVerified: "2026-07-20",
  },
  {
    id: "etherpad.list",
    module: "etherpad",
    method: "GET",
    path: "/iserv/etherpad",
    summary: "List visible Etherpads",
    description: "Loads visible collaborative pads without creating or editing one.",
    authentication: "session",
    sideEffect: "read",
    status: "supported",
    parameters: [],
    provenance: liveContract("sanitized normal-user GET contract"),
    lastVerified: "2026-07-20",
  },
  {
    id: "groupview.overview",
    module: "groupview",
    method: "GET",
    path: "/iserv/groupview",
    summary: "Read the group overview",
    description: "Loads groups visible to the account without joining, leaving, or editing them.",
    authentication: "session",
    sideEffect: "read",
    status: "supported",
    parameters: [],
    provenance: liveContract("sanitized normal-user GET contract"),
    lastVerified: "2026-07-20",
  },
  {
    id: "help.overview",
    module: "help",
    method: "GET",
    path: "/iserv/help",
    summary: "Read installed help",
    description: "Loads help documentation available on the configured instance.",
    authentication: "session",
    sideEffect: "read",
    status: "supported",
    parameters: [],
    provenance: liveContract("sanitized normal-user GET contract"),
    lastVerified: "2026-07-20",
  },
  {
    id: "office.overview",
    module: "office",
    method: "GET",
    path: "/iserv/office",
    summary: "Read office integration availability",
    description: "Loads the local office integration entry point without opening a document.",
    authentication: "session",
    sideEffect: "read",
    status: "supported",
    parameters: [],
    provenance: liveContract("sanitized normal-user GET contract"),
    lastVerified: "2026-07-20",
  },
  {
    id: "education.launch",
    module: "education",
    method: "GET",
    path: "/iserv/eduplacesconnector",
    summary: "Launch the education connector",
    description: "Represents an installed connector that redirects outside the selected instance.",
    authentication: "session",
    sideEffect: "read",
    status: "experimental",
    parameters: [],
    provenance: liveContract("external redirect detected; target intentionally not followed"),
    compatibility: "Not callable through the read-only executor because it leaves the instance.",
  },
  {
    id: "excalidraw.launch",
    module: "excalidraw",
    method: "GET",
    path: "/iserv/excalidraw",
    summary: "Launch Excalidraw",
    description: "Represents a navigation entry that was unavailable at its discovered local path.",
    authentication: "session",
    sideEffect: "read",
    status: "experimental",
    parameters: [],
    provenance: liveContract("installed-navigation discovery; local GET returned unavailable"),
  },
  {
    id: "conference.overview",
    module: "conference",
    method: "GET",
    path: "/iserv/videoconference",
    summary: "Read videoconference availability",
    description: "Loads the videoconference overview without creating or joining a room.",
    authentication: "session",
    sideEffect: "read",
    status: "supported",
    parameters: [],
    provenance: liveContract("sanitized same-origin redirect and GET contract"),
    lastVerified: "2026-07-20",
  },
  {
    id: "exercise.list",
    module: "exercise",
    method: "GET",
    path: "/iserv/exercise",
    summary: "List current exercises",
    description: "Loads the current exercises visible to the signed-in account.",
    authentication: "session",
    capability: "module:exercise",
    sideEffect: "read",
    status: "supported",
    parameters: [
      p("filter[search]", "query", false, "Optional exercise search"),
      p("filter[tag][]", "query", false, "Optional exercise tag"),
      p("sort[by]", "query", false, "Sort field exposed by the instance"),
      p("sort[dir]", "query", false, "Sort direction"),
    ],
    provenance: liveContract("sanitized normal-user GET contract"),
    lastVerified: "2026-07-20",
  },
  {
    id: "exercise.past",
    module: "exercise",
    method: "GET",
    path: "/iserv/exercise/past/exercise",
    summary: "List past exercises",
    description: "Loads the signed-in account's past-exercise overview without changing it.",
    authentication: "session",
    capability: "module:exercise",
    sideEffect: "read",
    status: "supported",
    parameters: [],
    provenance: liveContract("sanitized route discovery from exercise overview"),
    lastVerified: "2026-07-20",
  },
  {
    id: "exercise.show",
    module: "exercise",
    method: "GET",
    path: "/iserv/exercise/{id}",
    summary: "Read an exercise",
    description: "Loads one exercise visible to the account; this template awaits a live contract.",
    authentication: "session",
    capability: "module:exercise",
    sideEffect: "read",
    status: "experimental",
    parameters: [p("id", "path", true, "Exercise identifier")],
    provenance: liveContract("sanitized route-template discovery"),
    compatibility: "Discovered from an empty overview; detail response is not yet live-verified.",
  },
  {
    id: "timetable.overview",
    module: "timetable",
    method: "GET",
    path: "/iserv/timetable",
    summary: "Read the timetable overview",
    description: "Loads timetable and change sections visible to the signed-in account.",
    authentication: "session",
    capability: "module:timetable",
    sideEffect: "read",
    status: "supported",
    parameters: [],
    provenance: liveContract("sanitized normal-user GET contract"),
    lastVerified: "2026-07-20",
  },
  {
    id: "timetable.today",
    module: "timetable",
    method: "GET",
    path: "/iserv/timetable/data",
    summary: "Today's personal timetable",
    description:
      "Filters the personal week timetable down to one day (today by default) as a period list.",
    authentication: "session",
    capability: "module:timetable",
    sideEffect: "read",
    status: "supported",
    parameters: [p("date", "query", false, "Day as DD.MM.YYYY or YYYY-MM-DD (default: today)")],
    provenance: liveContract("timetable data filtered to one weekday"),
    lastVerified: "2026-07-20",
  },
  {
    id: "poll.list",
    module: "poll",
    method: "GET",
    path: "/iserv/poll",
    summary: "List visible polls",
    description: "Loads active poll information visible to the signed-in account.",
    authentication: "session",
    capability: "module:poll",
    sideEffect: "read",
    status: "supported",
    parameters: [],
    provenance: liveContract("sanitized normal-user GET contract"),
    lastVerified: "2026-07-20",
  },
  {
    id: "forums.list",
    module: "forums",
    method: "GET",
    path: "/iserv/forums",
    summary: "List visible forums",
    description: "Loads the forum index without marking topics or forums as read.",
    authentication: "session",
    capability: "module:forums",
    sideEffect: "read",
    status: "supported",
    parameters: [],
    provenance: liveContract("sanitized normal-user GET contract"),
    lastVerified: "2026-07-20",
  },
  {
    id: "news.list",
    module: "news",
    method: "GET",
    path: "/iserv/news",
    summary: "List visible news",
    description: "Loads visible news entries with optional server-side search.",
    authentication: "session",
    capability: "module:news",
    sideEffect: "read",
    status: "supported",
    parameters: [
      p("search", "query", false, "Optional news search"),
      p("show", "query", false, "Instance-provided display filter"),
    ],
    provenance: liveContract("sanitized normal-user GET contract"),
    lastVerified: "2026-07-20",
  },
  {
    id: "news.show",
    module: "news",
    method: "GET",
    path: "/iserv/news/show/{id}",
    summary: "Read a news entry",
    description: "Loads one news entry visible to the signed-in account.",
    authentication: "session",
    capability: "module:news",
    sideEffect: "read",
    status: "supported",
    parameters: [p("id", "path", true, "News entry identifier")],
    provenance: liveContract("sanitized normal-user GET contract"),
    lastVerified: "2026-07-20",
  },
  {
    id: "course_selection.list",
    module: "course-selection",
    method: "GET",
    path: "/iserv/courseselection",
    summary: "List available course selections",
    description: "Loads course selections currently visible to the signed-in account.",
    authentication: "session",
    capability: "module:course-selection",
    sideEffect: "read",
    status: "supported",
    parameters: [],
    provenance: liveContract("sanitized normal-user GET contract"),
    lastVerified: "2026-07-20",
  },
  {
    id: "mailing_lists.list",
    module: "mailing-lists",
    method: "GET",
    path: "/iserv/mailinglist",
    summary: "List visible mailing lists",
    description: "Loads mailing-list metadata without adding, editing, or deleting a list.",
    authentication: "session",
    capability: "module:mailing-list",
    sideEffect: "read",
    status: "supported",
    parameters: [],
    provenance: liveContract("sanitized normal-user GET contract"),
    lastVerified: "2026-07-20",
  },
  {
    id: "print.overview",
    module: "print",
    method: "GET",
    path: "/iserv/print",
    summary: "Read the print overview",
    description: "Loads print-job metadata without uploading or deleting a document.",
    authentication: "session",
    capability: "module:print",
    sideEffect: "read",
    status: "supported",
    parameters: [],
    provenance: liveContract("sanitized normal-user GET contract"),
    lastVerified: "2026-07-20",
  },
  {
    id: "pinboard.list",
    module: "pinboard",
    method: "GET",
    path: "/iserv/dsa-pinboard",
    summary: "List pinboard entries",
    description: "Represents the installed pinboard route when the current account may access it.",
    authentication: "session",
    capability: "module:pinboard",
    sideEffect: "read",
    status: "experimental",
    parameters: [],
    provenance: liveContract("installed-module discovery; current account denied or unavailable"),
    compatibility: "Installed module, but the current account did not receive a usable response.",
  },
  {
    id: "conference.health",
    module: "conference",
    method: "GET",
    path: "/iserv/videoconference/api/health",
    summary: "Read conference service health",
    description: "Returns health/capacity information exposed to the account.",
    authentication: "session",
    sideEffect: "read",
    status: "supported",
    parameters: [],
    provenance: upstream("src/Conference/ConferenceService.ts"),
    lastVerified: "2026-07-20",
  },
] satisfies RouteDefinition[];

export class RouteCatalog {
  readonly routes: readonly RouteDefinition[];
  constructor(routes: readonly RouteDefinition[] = ROUTES) {
    const ids = new Set<string>();
    for (const route of routes) {
      if (ids.has(route.id)) throw new Error(`Duplicate route id: ${route.id}`);
      ids.add(route.id);
    }
    this.routes = routes;
  }
  get(id: string): RouteDefinition {
    const route = this.routes.find((candidate) => candidate.id === id);
    if (!route) throw new Error(`Unknown route id: ${id}`);
    return route;
  }
  search(query: string, options: RouteSearchOptions = {}): RouteDefinition[] {
    const needle = query.trim().toLowerCase();
    const terms = needle.split(/\s+/).filter(Boolean);
    const limit = Math.max(1, Math.min(options.limit ?? this.routes.length, 1_000));
    return this.routes
      .filter(
        (route) =>
          (!options.module || route.module === options.module) &&
          (!options.method || route.method === options.method) &&
          (!options.sideEffect || route.sideEffect === options.sideEffect) &&
          (!options.status || route.status === options.status),
      )
      .map((route) => {
        const id = route.id.toLowerCase();
        const searchableId = id.replace(/[._-]+/g, " ");
        const module = route.module.toLowerCase();
        const path = route.path.toLowerCase();
        const summary = route.summary.toLowerCase();
        const description = route.description.toLowerCase();
        const haystack = `${id} ${module} ${path} ${summary} ${description}`;
        if (terms.some((term) => !haystack.includes(term))) return null;
        let score = 0;
        if (!needle) score = 1;
        else {
          if (id === needle) score += 200;
          if (searchableId === needle) score += 180;
          if (module === needle) score += 120;
          if (id.startsWith(needle)) score += 100;
          if (searchableId.startsWith(needle)) score += 90;
          if (summary.startsWith(needle)) score += 60;
          for (const term of terms) {
            if (id.includes(term)) score += 30;
            if (module.includes(term)) score += 20;
            if (path.includes(term)) score += 12;
            if (summary.includes(term)) score += 10;
            if (description.includes(term)) score += 4;
          }
        }
        return { route, score };
      })
      .filter((item): item is { route: RouteDefinition; score: number } => item !== null)
      .sort((a, b) => b.score - a.score || a.route.id.localeCompare(b.route.id))
      .slice(0, limit)
      .map(({ route }) => route);
  }
  modules(): string[] {
    return [...new Set(this.routes.map((route) => route.module))].sort();
  }
  tree(): Record<string, RouteDefinition[]> {
    return Object.fromEntries(
      this.modules().map((module) => [
        module,
        this.routes.filter((route) => route.module === module),
      ]),
    );
  }
}

export const routeCatalog = new RouteCatalog();
